# Generated by Django 4.1.5 on 2023-01-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registermodel',
        ),
    ]
