# Generated by Django 4.1.5 on 2023-01-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregistration',
        ),
    ]
