# Generated by Django 4.1.5 on 2023-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polldata',
            name='time',
        ),
        migrations.AddField(
            model_name='polldata',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
