# Generated by Django 4.1.5 on 2023-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_polldata_time_polldata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldata',
            name='time',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
